config/routes.rb
Rails.application.routes.draw do
  get 'members/dashboard'
  
  resources :last_known_cities
  resources :last_known_countries
  resources :locations
  resources :emotional_reactions

  resources :interaction_categories
  resources :interaction_types
  resources :interactions
  resources :categories
  resources :points
  resources :contact_types
  resources :contact_groups
  resources :contacts

  devise_for :users
  resources :users, only: [:show, :edit, :update, :destroy]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  authenticated :user do
    root 'pages#home', as: :authenticated_root
  end

  post 'search', to: 'search#index', as: 'search'
  post 'search/suggestions', to: 'search#suggestions', as: 'search_suggestions'
  get 'all_points', to: 'pages#all_points', as: 'all_points'
  get 'all_contacts', to: 'contacts#all_contacts', as: 'all_contacts'
  get 'support', to: 'pages#support', as: 'support'
  get 'admin', to: 'admin#index', as: 'admin'

  # Stripe checkout
  get 'checkout', to: 'checkouts#show'
  get 'checkout/success', to: 'checkouts#success'
  get 'checkouts/failure', to: 'checkouts#failure'
  get 'billing', to: 'checkouts#billing'

  root to: 'pages#index'

end

app/models/interaction_category.rb
class InteractionCategory < ApplicationRecord

	has_many :contact_categories, dependent: :destroy
	has_many :contacts, through: :contact_categories

	has_many :interact_interact_categories, dependent: :destroy
	has_many :interactions, through: :interact_interact_categories	

end

app/controllers/interaction_categories_controller.rb
class InteractionCategoriesController < ApplicationController
  before_action :set_interaction_category, only: %i[ show edit update destroy ]

  # GET /interaction_categories or /interaction_categories.json
  def index
    @interaction_categories = InteractionCategory.all
  end

  # GET /interaction_categories/1 or /interaction_categories/1.json
  def show
  end

  # GET /interaction_categories/new
  def new
    @interaction_category = InteractionCategory.new
  end

  # GET /interaction_categories/1/edit
  def edit
  end

  # POST /interaction_categories or /interaction_categories.json
  def create
    @interaction_category = InteractionCategory.new(interaction_category_params)

    respond_to do |format|
      if @interaction_category.save
        format.html { redirect_to interaction_category_url(@interaction_category), notice: "Interaction category was successfully created." }
        format.json { render :show, status: :created, location: @interaction_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @interaction_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interaction_categories/1 or /interaction_categories/1.json
  def update
    respond_to do |format|
      if @interaction_category.update(interaction_category_params)
        format.html { redirect_to interaction_category_url(@interaction_category), notice: "Interaction category was successfully updated." }
        format.json { render :show, status: :ok, location: @interaction_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @interaction_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interaction_categories/1 or /interaction_categories/1.json
  def destroy
    @interaction_category.destroy

    respond_to do |format|
      format.html { redirect_to interaction_categories_url, notice: "Interaction category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interaction_category
      @interaction_category = InteractionCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def interaction_category_params
      params.require(:interaction_category).permit(:name, :description)
    end
end

app/helpers/interaction_categories_helper.rb
module InteractionCategoriesHelper
end

app/views/interaction_categories/_form.html.erb
<%= form_with(model: interaction_category) do |form| %>
  <% if interaction_category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(interaction_category.errors.count, "error") %> prohibited this interaction_category from being saved:</h2>

      <ul>
        <% interaction_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, required: true  %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/interaction_categories/_interaction_category.html.erb
<div id="<%= dom_id interaction_category %>">
  <p>
    <strong>Name:</strong>
    <%= interaction_category.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= interaction_category.description %>
  </p>

</div>

app/views/interaction_categories/edit.html.erb
<div class="container">
  <div class="card">

    <div class="container">

      <h1>Editing interaction category</h1>

      <%= render "form", interaction_category: @interaction_category %>

      <br>

      <div>
        <%= link_to "Show this interaction category", @interaction_category %> |
        <%= link_to "Back to interaction categories", interaction_categories_path %>
      </div>

    </div>
  </div>
</div>

app/views/interaction_categories/index.html.erb
<div class="container">
  <div class="card">

    <div class="container">

      <p style="color: green"><%= notice %></p>

      <h1>Interaction categories</h1>

      <div id="interaction_categories">
        <% @interaction_categories.each do |interaction_category| %>
          <%= render interaction_category %>
          <p>
            <%= link_to "Show this interaction category", interaction_category %>
          </p>
        <% end %>
      </div>

      <%= link_to "New interaction category", new_interaction_category_path %>

    </div>
  </div>
</div>

app/views/interaction_categories/new.html.erb
<div class="container">
  <div class="card">

    <div class="container">

      <h1>New interaction category</h1>

      <%= render "form", interaction_category: @interaction_category %>

      <br>

      <div>
        <%= link_to "Back to interaction categories", interaction_categories_path %>
      </div>

    </div>
  </div>
</div>

app/views/interaction_categories/show.html.erb
<div class="container">
  <div class="card">

    <div class="container">

      <p style="color: green"><%= notice %></p>

      <%= render @interaction_category %>

      <div>
        <%= link_to "Edit this interaction category", edit_interaction_category_path(@interaction_category) %> |
        <%= link_to "Back to interaction categories", interaction_categories_path %>

        <%= button_to "Destroy this interaction category", @interaction_category, method: :delete %>
      </div>

    </div>
  </div>
</div>