config/routes.rb
Rails.application.routes.draw do
  get 'members/dashboard'
  
  resources :last_known_cities
  resources :last_known_countries
  resources :locations
  resources :emotional_reactions

  resources :interaction_categories
  resources :interaction_types
  resources :interactions
  resources :categories
  resources :points
  resources :contact_types
  resources :contact_groups
  resources :contacts

  devise_for :users
  resources :users, only: [:show, :edit, :update, :destroy]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  authenticated :user do
    root 'pages#home', as: :authenticated_root
  end

  post 'search', to: 'search#index', as: 'search'
  post 'search/suggestions', to: 'search#suggestions', as: 'search_suggestions'
  get 'all_points', to: 'pages#all_points', as: 'all_points'
  get 'all_contacts', to: 'contacts#all_contacts', as: 'all_contacts'
  get 'support', to: 'pages#support', as: 'support'
  get 'admin', to: 'admin#index', as: 'admin'

  # Stripe checkout
  get 'checkout', to: 'checkouts#show'
  get 'checkout/success', to: 'checkouts#success'
  get 'checkouts/failure', to: 'checkouts#failure'
  get 'billing', to: 'checkouts#billing'

  root to: 'pages#index'

end

app/models/last_known_city.rb
class LastKnownCity < ApplicationRecord

  has_many :contact_cities, dependent: :destroy
  has_many :contacts, through: :contact_cities

end

app/controllers/last_known_cities_controller.rb
class LastKnownCitiesController < ApplicationController
  before_action :set_last_known_city, only: %i[ show edit update destroy ]

  include Pagy::Backend

  # GET /last_known_cities or /last_known_cities.json
  def index
    @pagy, @last_known_cities = pagy(current_user.last_known_cities, items: 25)
  end

  # GET /last_known_cities/1 or /last_known_cities/1.json
  def show
  end

  # GET /last_known_cities/new
  def new
    @last_known_city = LastKnownCity.new
  end

  # GET /last_known_cities/1/edit
  def edit
  end

  # POST /last_known_cities or /last_known_cities.json
  def create
    @last_known_city = current_user.last_known_cities.new(last_known_city_params)

    respond_to do |format|
      if @last_known_city.save
        format.html { redirect_to last_known_city_url(@last_known_city), notice: "Last known city was successfully created." }
        format.json { render :show, status: :created, location: @last_known_city }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @last_known_city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /last_known_cities/1 or /last_known_cities/1.json
  def update
    respond_to do |format|
      if @last_known_city.update(last_known_city_params)
        format.html { redirect_to last_known_city_url(@last_known_city), notice: "Last known city was successfully updated." }
        format.json { render :show, status: :ok, location: @last_known_city }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @last_known_city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /last_known_cities/1 or /last_known_cities/1.json
  def destroy
    @last_known_city.destroy

    respond_to do |format|
      format.html { redirect_to last_known_cities_url, notice: "Last known city was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_last_known_city
      @last_known_city = LastKnownCity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def last_known_city_params
      params.require(:last_known_city).permit(:name)
    end
end

app/helpers/last_known_cities_helper.rb
module LastKnownCitiesHelper
end

app/views/last_known_cities/_form.html.erb
<%= form_with(model: last_known_city) do |form| %>
  <% if last_known_city.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(last_known_city.errors.count, "error") %> prohibited this last_known_city from being saved:</h2>

      <ul>
        <% last_known_city.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/last_known_cities/_last_known_city.html.erb
<div id="<%= dom_id last_known_city %>">
  <p>
    <strong>Name:</strong>
    <%= last_known_city.name %>
  </p>

</div>

app/views/last_known_cities/edit.html.erb
<h1>Editing last known city</h1>

<%= render "form", last_known_city: @last_known_city %>

<br>

<div>
  <%= link_to "Show this last known city", @last_known_city %> |
  <%= link_to "Back to last known cities", last_known_cities_path %>
</div>

app/views/last_known_cities/index.html.erb
<div class="container">
  <div class="card p-2">

    <p style="color: green"><%= notice %></p>

    <h1>Last known cities</h1>

    <div id="last_known_cities">
      <% @last_known_cities.each do |last_known_city| %>
        <%= render last_known_city %>
        <p>
          <%= link_to "Show this last known city", last_known_city %>
        </p>
      <% end %>
    </div>

    <%= link_to "New last known city", new_last_known_city_path %>

    <%== pagy_bootstrap_nav(@pagy) %>

  </div>
</div>

app/views/last_known_cities/new.html.erb
<div class="container">
  <div class="card p-2">

    <h1>Add New City</h1>

    <p>These are cities where a contact currently lives or was last seen.</p>
    <p>For example, if you met a lot of people in Shanghai, and you last remember these contacts to be living in Shanghai, add Shanghai as a city here.  Later, you will be able to know who of your contacts live where.</p>

    <%= render "form", last_known_city: @last_known_city %>

    <br>

    <div>
      <%= link_to "See All", last_known_cities_path %>
      <%= link_to "Home", root_path %>
    </div>

  </div>
</div>

app/views/last_known_cities/show.html.erb
<div class="container">
  <div class="card p-2">

    <p style="color: green"><%= notice %></p>

    <%= render @last_known_city %>

    <div>
      <%= link_to "Edit this last known city", edit_last_known_city_path(@last_known_city) %> |
      <%= link_to "Back to last known cities", last_known_cities_path %>

      <%= button_to "Destroy this last known city", @last_known_city, method: :delete %>
    </div>

  </div>
</div>