config/routes.rb
Rails.application.routes.draw do
  get 'members/dashboard'
  
  resources :last_known_cities
  resources :last_known_countries
  resources :locations
  resources :emotional_reactions

  resources :interaction_categories
  resources :interaction_types
  resources :interactions
  resources :categories
  resources :points
  resources :contact_types
  resources :contact_groups
  resources :contacts

  devise_for :users
  resources :users, only: [:show, :edit, :update, :destroy]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  authenticated :user do
    root 'pages#home', as: :authenticated_root
  end

  post 'search', to: 'search#index', as: 'search'
  post 'search/suggestions', to: 'search#suggestions', as: 'search_suggestions'
  get 'all_points', to: 'pages#all_points', as: 'all_points'
  get 'all_contacts', to: 'contacts#all_contacts', as: 'all_contacts'
  get 'support', to: 'pages#support', as: 'support'
  get 'admin', to: 'admin#index', as: 'admin'

  # Stripe checkout
  get 'checkout', to: 'checkouts#show'
  get 'checkout/success', to: 'checkouts#success'
  get 'checkouts/failure', to: 'checkouts#failure'
  get 'billing', to: 'checkouts#billing'

  root to: 'pages#index'

end

app/controllers/contact_types_controller.rb
class ContactTypesController < ApplicationController
  before_action :set_contact_type, only: %i[ show edit update destroy ]

  include Pagy::Backend

  # GET /contact_types or /contact_types.json
  def index
    @pagy, @contact_types = pagy(current_user.contact_types, items: 25)
  end

  # GET /contact_types/1 or /contact_types/1.json
  def show
  end

  # GET /contact_types/new
  def new
    @contact_type = ContactType.new
  end

  # GET /contact_types/1/edit
  def edit
  end

  # POST /contact_types or /contact_types.json
  def create
    @contact_type = ContactType.new(contact_type_params)
    @contact_type.user = current_user

    respond_to do |format|
      if @contact_type.save
        format.html { redirect_to contact_type_url(@contact_type), notice: "Contact type was successfully created." }
        format.json { render :show, status: :created, location: @contact_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_types/1 or /contact_types/1.json
  def update
    respond_to do |format|
      if @contact_type.update(contact_type_params)
        format.html { redirect_to contact_type_url(@contact_type), notice: "Contact type was successfully updated." }
        format.json { render :show, status: :ok, location: @contact_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_types/1 or /contact_types/1.json
  def destroy
    @contact_type.destroy

    respond_to do |format|
      format.html { redirect_to contact_types_url, notice: "Contact type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_type
      @contact_type = ContactType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_type_params
      params.require(:contact_type).permit(:name)
    end
end

app/helpers/contact_types_helper.rb
module ContactTypesHelper
end

app/views/contact_types/_contact_type.html.erb
<div id="<%= dom_id contact_type %>">
  <p>
    <strong>Name:</strong>
    <%= contact_type.name %>
  </p>

</div>

app/views/contact_types/_form.html.erb
<%= form_with(model: contact_type) do |form| %>
  <% if contact_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact_type.errors.count, "error") %> prohibited this contact_type from being saved:</h2>

      <ul>
        <% contact_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contact_types/edit.html.erb
<div class="container">
  <div class="card">

    <div class="container">

      <h1>Editing contact type</h1>

      <%= render "form", contact_type: @contact_type %>

      <br>

      <div>
        <%= link_to "Show this contact type", @contact_type %> |
        <%= link_to "Back to contact types", contact_types_path %>
      </div>

    </div>
  </div>
</div>    

app/views/contact_types/index.html.erb
<div class="container">
  <div class="card">

    <div class="mx-auto py-5">

      <p id="notive" style="color: green"><%= notice %></p>

      <h1>Contact Types</h1>

      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @contact_types.each do |contact_type| %>
            <tr>
              <td><%= contact_type.name %></td>
              <td><%= link_to 'S', contact_type %></td>
              <td><%= link_to 'E', edit_contact_type_path(contact_type) %></td>
              <td><%= link_to 'D', contact_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Contact Type', new_contact_type_path %>

    <%== pagy_bootstrap_nav(@pagy) %>

    </div>
  </div>
</div>

app/views/contact_types/new.html.erb
<div class="container">
  <div class="card">

    <div class="container">

      <h1>New Contact Type</h1>
      <p>Contact types are ways to categorize your contacts based on what they do.</p>
      <p>Here is a starter list of suggestions: Doctor, Pilot, Teacher, Publicist, Salesman, Web Developer, Fireman, Police Officer, Athlete, Speaker, Actor, Model, etc.  Think of all the people you know and what they do in life.  Then create a new contact type for each occupation or position.  You can always add more later.</p>

      <%= render "form", contact_type: @contact_type %>

      <br>

      <div>
        <%= link_to "See All", contact_types_path %>
        <%= link_to "Home", root_path %>
      </div>

    </div>
  </div>
</div>

app/views/contact_types/show.html.erb
<div class="container">
  <div class="card">

    <div class="mx-auto py-5">

      <p style="color: green"><%= notice %></p>

      <%= render @contact_type %>

      <div>
        <%= link_to "Edit this contact type", edit_contact_type_path(@contact_type) %> |
        <%= link_to "Back to contact types", contact_types_path %>

        <%= button_to "Destroy this contact type", @contact_type, method: :delete %>
      </div>

    </div>
  </div>
</div>